### ISSUE TITLE
New? Request Access

### ISSUE THREAD

**Issue by diamondstick** [StormlightTech/openCAD-php#113]
### Expected behavior
Let me sign up
### Actual behavior
Just breaks the login form
### Steps to reproduce behavior
Press the New? Request Access button and try to signup.

**Comment by murfasa** [comment]
What do you mean it just breaks the form? Any errors? Any error logs? Does it say anything?

**Comment by diamondstick** [comment]
No errors i just cant click anything

**Comment by murfasa** [comment]
Can I see a screenshot?

**Comment by murfasa** [comment]
Do you have the newest version?

**Comment by diamondstick** [comment]
Yes
https://gyazo.com/8ef2fa1ee9bd85d73c0eb8d8bce1cd4d

**Comment by murfasa** [comment]
Can I have the link to your site?

**Comment by termanator1128** [comment]
@murfasa I can confirm this error. Most likely the JS stuff that broke it.

**Comment by diamondstick** [comment]
I sent it to you on discord

**Comment by termanator1128** [comment]
This is due to a JS problem. Occurred after #101

**Comment by termanator1128** [comment]
Issue is fixed with #117
