### ISSUE TITLE
000webhost gives a   page cant be loaded

### ISSUE THREAD

**Issue by CourtneyKitty** [StormlightTech/openCAD-php#114]
i have uploaded the files and did the changes  that need to be done and i get a  500 code and it says it cant do it at this time and i dont know way its doing it

**Comment by rhys19** [comment]
i use ubuntu 16.04 show same thing but look up my ip on a windows desktop but on ubuntu all i get is white screen hope someone can help

**Comment by rhys19** [comment]
loded spelled wrong its loaded

**Comment by Cambridgeport90** [comment]
@rhys19 
That's hilarious; surprised I didn't see it; after all, I'm a bit of a grammar queen; graduating with an English degree does that.

**Comment by murfasa** [comment]
Have you set up the database? Can you send error logs? It's usually in the actions folder.

**Comment by CourtneyKitty** [comment]
yes the database was set up and i can lok once  it lets me see the files

**Comment by murfasa** [comment]
Does this happen when you try to access a page, when you login, or sometime else?

**Comment by Ramius1701** [comment]
I will create a free account with 000webhost later this evening to see if i can help figure out whats going on. Since this is becoming an increasing issue

**Comment by CourtneyKitty** [comment]
i cant evein log in

**Comment by CourtneyKitty** [comment]
i have no log in that  folder i jest looked  and it stell dose   this This page isn’t working

mythicalabamadpsrp.000webhostapp.com is currently unable to handle this request.
HTTP ERROR 500 and i have   it set to localhost do i need it to say http:localhost/

**Comment by termanator1128** [comment]
I suggest you stop using 000webhost. There are a bunch of issues with it.

**Comment by dwhirsch** [comment]
God the SR moderator recommends going with this host 
https://www.hostblast.net/web-hosting/
it only costs 50c so stop trying to use free hosts as they wont support what your trying to do

**Comment by phillf** [comment]
I am closing this before this becomes an argument over what hosts are better.

**Comment by CourtneyKitty** [comment]
so is there  a way for me to fix it or not

**Comment by termanator1128** [comment]
No. Let me put it this way. 000Webhost is not supported and will not work. End of discussion.
