### ISSUE TITLE
Suggestions: MDT Change / Civ Identity Edit

### ISSUE THREAD

**Issue by ACBobby** [StormlightTech/OpenCAD-php#132]
I'd like to see the ability of self-assigning and clearing of calls removed from the MDT side. It makes no sense for an Officer to self-dispatch themselves to an open call, or to be able to clear one in progress.

It'd also be great if a civilian could edit their identity. Currently this isn't possible.

In addition, there should be a flag to allow civilians to make an identity without needing it to be approved.

**Comment by termanator1128** [comment]
@ACBobby Please be aware that this is still in Pre-Aplha and everything is subject to change.
