### ISSUE TITLE
Bug: Admins Group Doesn't Give Admin Access

### ISSUE THREAD

**Issue by ACBobby** [StormlightTech/OpenCAD-php#136]
Giving someone the Admins group instead of Head Administrator doesn't allow them access to the Admin panel.

Also: Just as a side suggestion, it'd be super awesome to just have a group solely dedicated to being allowed to approve MDT/CAD user requests instead of having to give them full Admin access.

**Comment by termanator1128** [comment]
@ACBobby Keep in mind this is still a Pre-Alpha.
