### ISSUE TITLE
Introduce an online installer to automate deployment.

### ISSUE THREAD

**Issue by KC1KAD** [StormlightTech/OpenCAD-php#14]
_From @ItsAGeekThing on September 3, 2017 1:36_

Introduce an installer to automated deployment.

_Copied from original issue: phillf/openCad#23_

**Comment by ItsAGeekThing** [comment]
I will begin working on this later today.

**Comment by ItsAGeekThing** [comment]
_From @phillf on September 3, 2017 14:42_

Excellent. Once we have a working installer I will revise the install instructions on the Wiki.

**Comment by ItsAGeekThing** [comment]
Giving myself a deadline for this particular issue.
Alpha Release by 9/14/2017 at the latest.

**Comment by ItsAGeekThing** [comment]
I would like to note that I have made progress on this.
It's currently on a uncommitted offline branch.
