### ISSUE TITLE
Adding subusers

### ISSUE THREAD

**Issue by KC1KAD** [StormlightTech/OpenCAD-php#2]
_From @justinfarmer14 on August 30, 2017 5:49_

Issues adding assigned users to additional departments

_Copied from original issue: phillf/openCad#5_

**Comment by ItsAGeekThing** [comment]
_From @justinfarmer14 on August 30, 2017 6:1_

![user groups 1](https://user-images.githubusercontent.com/31464982/29857522-b543dc36-8d1e-11e7-8800-b9544b7a05ba.png)

a work around i found was copying the head admin department id since i assigned all departments to my self
