### ISSUE TITLE
Application Icon Set

### ISSUE THREAD

**Issue by phillf** [StormlightTech/openCAD-php#31]
Improving the graphics set of openCAD would be a good idea. We definitely need a logo and icons for each subsequent application.

**Comment by phillf** [comment]
This is sort of what I'd like to see: https://images-ext-2.discordapp.net/external/KSr1wLVhFKAu6UCmV2xPiBHwtI1uBRcnG8TfScjJSZw/%3Fq%3Dtbn%3AANd9GcTSLptjors2BKht5nDgYsyRlA5UIJFPIF-RM5pVp3RmWq6cKXKIQQ/https/encrypted-tbn0.gstatic.com/images

I am thinking for icon colors:
- Red for fire
- Blue for PD
- Gold for Sheriff
- Green (maybe) for State Police/Highway
- Silver for Civilian

For the openCAD icon keep the casing and do a O in a deep, rich blue.

**Comment by murfasa** [comment]
This is something I'll work on!

**Comment by phillf** [comment]
I would make the icons 512x512. We can scale them down after.

**Comment by murfasa** [comment]
I'll do a Gray-ish color for Civilian rather than Silver, just looks better.

**Comment by phillf** [comment]
Commit #99 closes this.
