### ISSUE TITLE
Installation step 3 of 11 site just refreshes

### ISSUE THREAD

**Issue by moltren** [StormlightTech/OpenCAD-php#352]
The site just refreshes when i press continue.
Reinstalled like 10 times, the 5 time it worked but then the sql wouldent load so someone from the support team told me to reinstall and i did then this happend.

https://gyazo.com/e96f618304614e1a76ac3b25569ef60b

**Comment by phillf** [comment]
Not quite sure why you are raising this here. They should have raised it as a bug in the JIRA and provided you with a link to the issue so you can monitor it.

I am going to look in to this issue right now. You can [find the aforementioned issue in JIRA here](https://jira.opencad.io/browse/OCPHP-724).
