### ISSUE TITLE
Step 5 of 11 - Authentification key is blank

### ISSUE THREAD

**Issue by ItsLukass** [StormlightTech/OpenCAD-php#355]
So i just got the open cad and I'm trying to set it up but when I go to the step 5 I don't see where can I put the auth key nor the back and continue buttons show up
I also upgraded to PHP 7.3 from 7.0 ( did a clean wipe of PHP 7.0)
running it on apache 2
Os : debian 9

screenshot: https://gyazo.com/4737acc9ba5d55f5ca1200955907e56c

**Comment by ItsLukass** [comment]
Found the fix: i accidentally installed php 7.4 not 7.3 and when I downgraded to 7.3 that seems to have fixed the issue

**Comment by Cambridgeport90** [comment]
Correctly: "authentication" ...

**Comment by phillf** [comment]
@ItsLukass, OC does work with PHP 7.4. My local test environment is 7.4.7.

[These are the PHP modules I have enabled](https://i.imgur.com/69Q79jD.png). Please let me know if this helps.
