### ISSUE TITLE
Can't install - get stuck on Database settings screen

### ISSUE THREAD

**Issue by TechPhil** [StormlightTech/OpenCAD-php#356]
I'm trying to install OpenCAD, but I can't get past the 'Database settings screen'
I set all the settings correctly - The Test Connection button confirms this, although does not show visually on the screen,
Whenever I click 'Continue', i get sent to the same page, but without any information filled in and a different database prefix.

Honestly not sure what to do about this one.

**Comment by TechPhil** [comment]
Furthermore, whenever I reinstall OC from scratch, the information I inputted from the previous steps are pre-filled, despite a full reinstall

**Comment by devotedsouls** [comment]
Hey @TechPhil,
Please move this into our discord and we will be glad to assist you.
