### ISSUE TITLE
NCIC Admin NamesDB information flipped

### ISSUE THREAD

**Issue by Sharky521** [StormlightTech/OpenCAD-php#357]
In the NCIC NamesDB, Build and DL Status is reversed.
In ncicAdminActions.php, line 120 should be flipped with line line 122 as "Build" currently shows it's value under "DL Status" and vice versa.

**Comment by devotedsouls** [comment]
Hello Sharky521,

Thanks for submitting this bug report! We'll assign it to a developer and get back to you as soon as possible!

**Comment by devotedsouls** [comment]
Hey Shark!

We've made a commit to resolve this issue. It'll be published when we make the next release.
