### ISSUE TITLE
Undefined index: PHP_AUTH_DIGEST

### ISSUE THREAD

**Issue by GaneshKandu** [StormlightTech/OpenCAD-php#362]
**Describe the bug**
getting blank screen when access

**To Reproduce**
1. its working when fresh install
2. but not working after clearing the cookie

**Screenshots**
blank screem

**Desktop (please complete the following information):**
 - OS: Centos 6 
 - Browser Firefox 86.0b7 (64-bit)

**Additional context**
this is error
```
Array
(
    [type] => 8
    [message] => Undefined index: PHP_AUTH_DIGEST
    [file] => /home/script/public_html/open356/plugins/api_auth.php
    [line] => 25
)
```

**Comment by devotedsouls** [comment]
Hey @GaneshKandu,
I am trying to troubleshoot and reproduce this error on my side, is there any way you can provide a more in-depth guide as to how you found this error.

Thank you very much,

Shealynn Stocking

**Comment by GaneshKandu** [comment]
@devotedsouls 
I think firefox doesn't sending a digest authorization
header.
you should try reproducing this error on firefox browser.

**Comment by Cambridgeport90** [comment]
That's odd that it's only Firefox. How about others? I need to set my testing environment back up.
