### ISSUE TITLE
Table Columns on Civlian Dashboard

### ISSUE THREAD

**Issue by AniTexs** [StormlightTech/OpenCAD-php#366]
**Describe the bug**
When logged in as a civilian and you've created and the "My Identities" table has one too many columns in the content than the header.
This is caused by the function ncicGetNames() in civActions.php between lines 124 and 162.

**To Reproduce**
1. Go to Civilian
2. Create a new identity
3. View the new Identity under "My Identities"

**Expected behavior**
The table header has the same column count as the content.

**Screenshots**
No Screenshots since this should be easy to recreate

**Desktop (please complete the following information):**
 - Browser [Brave]

**Comment by AniTexs** [comment]
Image showing the problem

![image](https://user-images.githubusercontent.com/10406786/108839185-05c1c180-75d5-11eb-9275-670decf825ea.png)


Image showing the problem in the code
![image](https://user-images.githubusercontent.com/10406786/108839295-2ee25200-75d5-11eb-9956-a5e3f4c7750a.png)

**Comment by ItsAGeekThing** [comment]
Hi @AniTexs,
Thanks for the report.

Any chance you can confirm the exact version of OpenCAD you are running (e.g., "_0.3.2-HOTFIX362_")?

Cheers,
Justin

**Comment by AniTexs** [comment]
The newest version so yes it's 0.3.2 Hotfix 362

**Comment by phillf** [comment]
I swear I had fixed this before. I will take a look right now.

**Comment by phillf** [comment]
This is addressed with PR #372. @mikespears and @devotedsouls. If you could check it over that would be appreciated.

**Comment by phillf** [comment]
This is sorted in the linked #376 PR.
