### ISSUE TITLE
Weapon Tables Incorrect

### ISSUE THREAD

**Issue by Sharky521** [StormlightTech/OpenCAD-php#368]
**Describe the bug**
The weapons under Civilian and all other locations of the CAD relating to weapons show the combination of Name and Type in the same Row instead of their individual rows.

**To Reproduce**
1. Go to 'Civilian Dashboard'
2. Click on 'Add Weapon' and add any weapon
3. Scroll down to 'My Weapons'
4. Weapon Names and Types show both in each column
5. Go to 'Admin Dashboard'
6. Scroll down to 'NCIC Weapons' and see the same issue

**Expected behavior**
Weapon Names and Types should show in their correct tables instead of seeing the type and name in both tables

**Screenshots**
![image](https://user-images.githubusercontent.com/36453777/109338106-7104d100-782b-11eb-8320-4f5e0f764fbe.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 v2004
 - Browser: Chrome/Edge/Firefox
 - Version: latest

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser: All
 - Version: Latest

**Additional context**
N/A

**Comment by ItsAGeekThing** [comment]
Hi @Sharky521,
Thanks for the report.

Any chance you can confirm the exact version of OpenCAD you are running (e.g., "_0.3.2-HOTFIX362_")?

Cheers,
Justin

**Comment by Sharky521** [comment]
@ItsAGeekThing 
You are welcome. My current version is OpenCAD Version 0.3.2 Update 01/15/2021
The same issue is present on older versions. I actually wasn't aware that there was a new hotfix. Let me try those files first.
After looking through the code, there doesn't seem to be any difference so I'm willing to bet the issue will remain the same.

**Comment by ItsAGeekThing** [comment]
Hi @Sharky521,
I have reproduced this in my test environment and will raise it with the team.

Cheers,
Justin

**Comment by phillf** [comment]
@Sharky521, do you recall what version you were running when you encountered this issue?

**Comment by Sharky521** [comment]
Last I checked it was still an issue on the 0.3.2 Hotfix update. It was identified in the 0.3.2 1/15 update but was confirmed to still be an issues in the following HotFix.
