### ISSUE TITLE
SQL Weapon Permit options spelling

### ISSUE THREAD

**Issue by Sharky521** [StormlightTech/OpenCAD-php#369]
**Describe the bug**
There is a misspelled option in the weapon_permit table options

**To Reproduce**
1. Go to '/sql'
2. Click on 'oc_install.sql'
3. Scroll down to 'line 173'
4. See error - Vaild should be spelled Valid

**Expected behavior**
Correct spelling of Valid

**Screenshots**
Not Needed

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
See Pull Request 149352a on Canary Build

**Comment by Cambridgeport90** [comment]
If you guys need proofreaders for text... I'm willing. Just say the word and I'll do stuff.

**Comment by phillf** [comment]
Not sure when this was fixed but this issue can be closed.
