### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by PC1up** [StormlightTech/OpenCAD-php#370]
**Describe the bug**

**To Reproduce**
1. Install OpenCAD on your localhost via XAMPP
2. Go to 'localhost/oc-install/start.php'
3. The error popped up

**Expected behavior**
I guess it should not display an error.

**Screenshots**
Error: https://just-paste.it/NRLz5O4QIW

**Desktop (please complete the following information):**
 - OS: Windows 10.0.18363
 - Browser: Opera GX
 - Version: latest

**Additional context**
None

**Comment by phillf** [comment]
@PC1up, same thing here as in #371, please define the precise version.

**Comment by PC1up** [comment]
The error fixed itself... Somehow...
