### ISSUE TITLE
MySQL Table problem & Dispatch Menu & Civilian Menu everything unclickable (read comment)

### ISSUE THREAD

**Issue by PC1up** [StormlightTech/OpenCAD-php#371]
**Describe the bug**
I newly installed OpenCAD and for some reason, OpenCAD creates tables named "... type**s**" but need tables named "... type". So I renamed the MySQL tables in phpMyAdmin but now there are no warrant types or anything else, even if I reset the table. There is also a minor bug that when you're in the Warrant Type Manager (after reproducing the bug) you can't open the Game Data Manager again so you have to go for example to the User Management and can go further from there.

**To Reproduce**
1. Install OpenCAD
2. Go to the admin panel
3. Click on Game Data Manager
4. Click "Import/Export/Reset"
5. Choose "Warrant Types"
6. It should display, that the table "..._warrant_type" doesn't exist
7. Rename the table in phpMyAdmin
8. There are no warrant types now

**Expected behavior**
It shouldn't create wrong named tables.

**Screenshots**
The error with "..._type" doesn't exist: https://prnt.sc/10wv19k
Screenshot of the Warrant Type Manager in the admin panel: https://prnt.sc/10wvf4p

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Version latest

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser Any
 - Version Any

**Additional context**
None

**Comment by PC1up** [comment]
Okay, I managed to fix some things and implemented the default departments, etc. succesfully except the incident types, the citation types and the warrant types. If I try to manage them in the admin panel there is no content (https://prnt.sc/10x30cp || phpMyAdmin warrant types table: https://prnt.sc/10x30tu).
I also got a new error. I can't do anything in the dispatch menu and in the civilian menu. There is content but I can't click anywhere.

**Comment by phillf** [comment]
@PC1up Can you actually define what version you are on rather than using the word "latest". I want to be 100% sure I am pulling that same release that you are.

**Comment by PC1up** [comment]
idk if this is the right one but in my browser it says
"OpenCAD Version 0.3.2 Update"

**Comment by phillf** [comment]
Okay. I think that is the HOTFIX362 release. Not 100% sure though.

Can you try with https://github.com/opencad-app/OpenCAD-php/releases/tag/0.3.2-hotfix362 or let me know if this was indeed what you pulled and delpoyed?

**Comment by PC1up** [comment]
That (https://github.com/opencad-app/OpenCAD-php/releases/tag/0.3.2-hotfix362) is the one I'm using.

**Comment by phillf** [comment]
@PC1up, are you deploying OC into production or are you just testing it? If it's the later I'd ask you to take a look at [the codebase from tee canary branch of @ItsAGeekThing's repo](https://github.com/ItsAGeekThing/OpenCAD-php) and report back. The two of us have made considerable progress towards 1.0 and would appreciate some outside input.

I give you fair warning though... be prepared for some things to be broken. As always please raise the corresponding bug reports.
