### ISSUE TITLE
Proposal to drop support for old versions of PHP.

### ISSUE THREAD

**Issue by ItsAGeekThing** [StormlightTech/OpenCAD-php#374]
**Synopsis**
OpenCAD's officially supports PHP 7.3 (currently recommended release) and PHP 7.2 (minimum) per our current documentation.
Running older versions of PHP may expose servers to security vulnerabilities and children eating bugs that would have otherwise already been fixed on current PHP branches. 

PHP 7.2 (OpenCAD's minimum supported PHP branch) has reached [end of life](https://www.php.net/eol.php) and received its last update on 11/30/2020

PHP 7.3 while not end of life is [no longer actively supported](https://www.php.net/supported-versions.php) and will only receive critical security fixes going forward (EOL on 12/6/2021).

**Where do we begin?**
We need to first verify OpenCAD's compatibility with the currently "maintained" branches of PHP (E.g., "7.3, 7.4, and 8.0") before making any further decisions. Should everything work right of the get go, we can proceed directly to receiving community feedback. Should things not be working as expected, we should go ahead and opened the relevant bug reports and pull requests without introducing regressions if possible.

**What do we do after?**
Once we shift OpenCAD's officialy supported branches of PHP to maintained versions we should begin to follow PHP's [active support window](https://www.php.net/supported-versions.php) going forward.

**What other considerations must we discuss before making any changes?**
While this is a minor change in principle, the fact is that there are so many different environments being utilized by our community. 

Unfortunately, a good amount of shared hosting providers does not offer the currently supported versions of PHP to their customers for a variety of reasons.

***

The PHP Group. (n.d.). PHP: Supported Versions. PHP. Retrieved March 28, 2021, from https://www.php.net/supported-versions.php

The PHP Group. (n.d.-b). PHP: Unsupported Branches. PHP. Retrieved March 28, 2021, from https://www.php.net/eol.php

**Comment by phillf** [comment]
I would argue that we NEED to follow PHP's support window with the following caveat. They seem to post their initial release around November/December, given this I would suggest preparing to shift up from the recommended at least 3-5 moths ahead of November for the given release year.

**Comment by ItsAGeekThing** [comment]
> I would argue that we NEED to follow PHP's support window with the following caveat. They seem to post their initial release around November/December, given this I would suggest preparing to shift up from the recommended at least 3-5 moths ahead of November for the given release year.

July might be a good month (going forward) as this marks the beginning of Quarter 3.

**Comment by mikespears** [comment]
I totally agree with dropping support for PHP 7.2

> Unfortunately, a good amount of shared hosting providers does not offer the currently supported versions of PHP to their customers for a variety of reasons.


From what I've seen, most reasonable providers default to at least 7.3, if not 7.4.

**Comment by ItsAGeekThing** [comment]
> I totally agree with dropping support for PHP 7.2
> 
> > Unfortunately, a good amount of shared hosting providers does not offer the currently supported versions of PHP to their customers for a variety of reasons.
> 
> 
> From what I've seen, most reasonable providers default to at least 7.3, if not 7.4.

The last time I utilized shared hosting personally this was not the case (albeit this was a few years ago), so that is good to hear that this is no longer the case.

I suppose the next step is to confirm OpenCAD's compatibility with PHP 7.4 and 8.0 and raise the relevant bug reports if anything comes up.

**Comment by phillf** [comment]
> > I totally agree with dropping support for PHP 7.2
> > > Unfortunately, a good amount of shared hosting providers does not offer the currently supported versions of PHP to their customers for a variety of reasons.
> > 
> > 
> > From what I've seen, most reasonable providers default to at least 7.3, if not 7.4.
> 
> The last time I utilized shared hosting personally this was not the case (albeit this was a few years ago), so that is good to hear that this is no longer the case.
> 
> I suppose the next step is to confirm Open dad's compatibility with PHP 7.4 and 8.0 and raise the relevant bug reports if anything comes up.

I am reasonably certain it is compatible with 7.4. I have been developing against 7.4 this entire time. Precise version is 7.4.7.

Current the version checking code check for versions 7.2<. This controlled by the constant OC_VERSION in oc-includes/version.php.

**Comment by phillf** [comment]
Per staff meeting on Sunday 4 April 2021 the decision was made to follow PHP's EOL release cadence.

As of this post 1.0 will Ask for PHP 7.3 MINIMUM and PHP 7.4 RECOMENDED. PHP 8.0 is in the process of being tested against.
