### ISSUE TITLE
Make sure creating this cookie without the "secure" flag is safe

### ISSUE THREAD

**Issue by phillf** [StormlightTech/OpenCAD-php#382]
**Describe the bug**
Make sure creating this cookie without the "secure" flag is safe here.

**To Reproduce**
No EU interaction required.

**Expected behavior**
Secure cookie transport. Result isn't visible to EU.

**Additional context**
[Sonar Cloud issue](https://sonarcloud.io/project/security_hotspots?id=opencad-app_OpenCAD-php&hotspots=AXh7qemZiIV3naYkCysP)
[Sonar Cloud issue](https://sonarcloud.io/project/security_hotspots?id=opencad-app_OpenCAD-php&hotspots=AXh7qel8iIV3naYkCypg)
[Sonar Cloud issue](https://sonarcloud.io/project/security_hotspots?id=opencad-app_OpenCAD-php&hotspots=AXh7qelJiIV3naYkCynr)

**Comment by phillf** [comment]
This also goes hand in hand with #379.

**Comment by ItsAGeekThing** [comment]
The referenced Sonar Cloud issues have been marked as fixed.

**Comment by ItsAGeekThing** [comment]
This issue is still present in 1.0.0

---

[Sonar Cloud issue](https://sonarcloud.io/project/security_hotspots?id=ItsAGeekThing_OpenCAD-php&hotspots=AXif9tGk-0-05NCJBRjy)
[Sonar Cloud issue](https://sonarcloud.io/project/security_hotspots?id=ItsAGeekThing_OpenCAD-php&hotspots=AXijUszHrJg7f_SWYovO)
[Sonar Cloud issue](https://sonarcloud.io/project/security_hotspots?id=ItsAGeekThing_OpenCAD-php&hotspots=AXif9tHI-0-05NCJBRkt)

**Comment by phillf** [comment]
@ItsAGeekThing, do you know if this still exists in release/canary?

**Comment by ItsAGeekThing** [comment]
> @ItsAGeekThing, do you know if this still exists in release/canary?

I'll go ahead and verify.

**Comment by ItsAGeekThing** [comment]
I have reviewed the Sonar Cloud report and the following lines now show the secure flag set.

https://github.com/opencad-app/OpenCAD-php/blob/6fe532b4d691078b81a6488a9c5129f761d2776c/oc-includes/generalActions.php#L81
https://github.com/opencad-app/OpenCAD-php/blob/6fe532b4d691078b81a6488a9c5129f761d2776c/oc-includes/login.php#L169
https://github.com/opencad-app/OpenCAD-php/blob/6fe532b4d691078b81a6488a9c5129f761d2776c/oc-includes/logout.php#L51

We still need to review the rest of the code base to ensure there were no regressions (and a new issue if necessary) but for the purpose of this issue, this is resolved.
