### ISSUE TITLE
User Management Screen

### ISSUE THREAD

**Issue by devotedsouls** [StormlightTech/OpenCAD-php#388]
**Describe the bug**
User management screen does not pull up correctly

**To Reproduce**
1. Login onto an account
2. Click on 'User management" 
3. See error

**Expected behavior**
User management page to pull up

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Enterprise
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 87.0.0

**Comment by phillf** [comment]
@devotedsouls, can you clarify what you mean by "User management screen does not pull up correctly".
