### ISSUE TITLE
NCIC Editor

### ISSUE THREAD

**Issue by devotedsouls** [StormlightTech/OpenCAD-php#389]
**Describe the bug**
NCIC Editor does not load, loads into error page.

**To Reproduce**
1. Go to 'Admin Dashboard'
2. Click on 'NCIC Editor' 
3. See error

**Expected behavior**
Loads the NCIC error page

**Screenshots**
Error Page
![image](https://user-images.githubusercontent.com/40869809/114242866-337a8400-9951-11eb-8adc-77d9e5e06fec.png)

**Comment by phillf** [comment]
I will update the oc_install.sql style but the fix is to add that column to the ncicWeapons table. If it already exists then just tweak the name.

**Comment by phillf** [comment]
Looking at oc_install.sql there is a column named weaponPermit. This needs to be named weaponPermitStatus.


The next two columns after that should be:
- weaponPermitType
- weaponPermitIssuedBy

These currently have underscores in them. The need to be renamed to align with the new database spec. I just tweaked to oc_install.sql file and am going to push it in a couple of minutes.
