### ISSUE TITLE
[PROPOSAL] Deprecate passwordReset column in users table in favour of adding a new status to approved.

### ISSUE THREAD

**Issue by phillf** [StormlightTech/OpenCAD-php#394]
**Describe the solution you'd like**
1. Deprecate the _passwordReset_ column in the users table. 
2. Rename the _approved_ column to _accountStatus_.
3. Introduce new status of 3 which would correspond to "User must reset password upon next login".

**Comment by phillf** [comment]
I am also thinking that that when a user is unsuspended their password should be changed to something completely random and a password reset upon next login should be forced.

This would require an email to be sent to the user upon suspension deprecation.

**Comment by ItsAGeekThing** [comment]
> I am also thinking that that when a user is unsuspended their password should be changed to something completely random and a password reset upon next login should be forced.
> 
> This would require an email to be sent to the user upon suspension deprecation.

This might be something that should be split into a separate issue/proposal.

**Comment by phillf** [comment]
The underlying problem with this is that the reset password facility isn't currently implemented.

**Comment by phillf** [comment]
I will create another issue for the implementation of a Password reset workflow.

Later on I will pull out the column in question as it doesn't serve a purpose.

**Comment by devotedsouls** [comment]
This ticket has been split into two issues.

Ticket #398 
Ticket #399
