### ISSUE TITLE
Ncic actions 

### ISSUE THREAD

**Issue by KC1KAD** [StormlightTech/OpenCAD-php#4]
_From @justinfarmer14 on August 30, 2017 5:59_

unable to edit any of user data in ncic data base 
![ncic error edit](https://user-images.githubusercontent.com/31464982/29857463-67131464-8d1e-11e7-8486-7b716ce0f575.png)

_Copied from original issue: phillf/openCad#8_

**Comment by ItsAGeekThing** [comment]
_From @Ramius1701 on August 31, 2017 2:19_

While i am able to edit after clicking the edit button the adminActions.php is blank and nothing changes
