### ISSUE TITLE
[PROPOSAL] Drop Support for PHP 7.3 at end of January

### ISSUE THREAD

**Issue by phillf** [StormlightTech/OpenCAD-php#407]
Per PHP's EOL documentation v. 7.3 was EOL on 1 January 2020.

8.0 should be recommended and 7.4 should be the minimum.

**Comment by Cambridgeport90** [comment]
Have we tested with PHP 8? I recall some issues with it in the past… but I haven’t been following as much as I probably should.

From: Phill Fernandes ***@***.***>
Sent: Saturday, December 18, 2021 11:15 AM
To: opencad-app/OpenCAD-php ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [opencad-app/OpenCAD-php] [PROPOSAL] Drop Support for PHP 7.3 at end of January (Issue #407)


Per PHP's EOL documentation v. 7.3 was EOL on 1 January 2020.

8.0 should be recommended and 7.4 should be the minimum.

**Comment by phillf** [comment]
@Cambridgeport90 This is meant for v. 1.0 specifically.

**Comment by Cambridgeport90** [comment]
Ah okay…
