### ISSUE TITLE
The status of the officer is not displayed

### ISSUE THREAD

**Issue by AAndersenLves** [StormlightTech/OpenCAD-php#426]
**Describe the error**
A clear and concise description of what constitutes an error.

**For Playback**
1. Go to "State Patrol or State Police or other user mode"
2. Click on the "Change Status" button
3. Change the status 
4. Nothing changes in the My Status column, at the same time, the dispatcher changes it as available, but after a while the unit disappears from the dispatcher panel

**Expected behavior**
Status change in the My Status column, status change in the dispatcher panel

**Screenshots**

**Desktop (please fill in the following information):**
 - OPERATING system: [e.g. iOS] Windows 10
- - Browser [e.g. chrome, safari] Chrome | Firefox | edge
 - Version [e.g. 22] 102.0.5005.115

**Additional context**

I can't attach a screenshot, because here it is necessary to check in reality. Access for administration

Login: test@gmail.com
Password: qwerty123

Website: http://lves.h1n.ru/

**Comment by phillf** [comment]
Bug report filed incorrectly. Closing thread.
