### ISSUE TITLE
Features ,suggestions, bugs whatever you like to call these.

### ISSUE THREAD

**Issue by BrokenGabe** [StormlightTech/OpenCAD-php#433]
After first installation, when logging into dashboard as admin, admin should see all group access functions.

Registration:
Signup and civreg should both be the same thing, all new accounts should automatically be registration for civilian access.
 
Groups accepting people should be displayed on a separate "application" page after a person registered as a civilian.

Group registration should have an agreement page per-group for applicants to read when they "apply" for that group. Editable by Mods or Admins.

The individual groups page should have an applications received page to accept or deny applications to that group.

Admin:
Should have a moderator roll that can moderate the groups different pages.

"Dashboard" should be renamed to Admin Home or such. confusing when the login page is also called Dashboard.

User Management for Admins does not have a feature to change users groups. After I installed mine and made a test user, it never defaulted to CIV (it should). and when I went to change that test user to sheriff, there is no option to do so. I had to manually enter the database and add the options I want. This all should be do-able as admin.

Page displaying all group "applications" and their status.

Game Data Management:
Warning Types Manager should have some predefined default warnings with the ability to add more.

Warrant Types Management: prefilled with 0s and 1s, should be actual warrant types with the ability to add more.

I'll add more if I think of it.

**Comment by ItsAGeekThing** [comment]
What version of OpenCAD do you have deployed?

**Comment by phillf** [comment]
Given there has been no response or attempt at clarification since @ItsAGeekThing's response on 2022 September 4 this thread is being closed.

Furthermore, please raise separate issues for each bug or feature request.
