### ISSUE TITLE
Since when is CAD not to do with Computer-Aided Design ?

### ISSUE THREAD

**Issue by Wrexham244th** [StormlightTech/OpenCAD-php#435]
I'm confused.

This reeks of intentional "SEO  Pollution".

**Comment by kevingorman1000** [comment]
Since for like ever? 

https://www.google.com/url?q=https://www.dhs.gov/sites/default/files/publications/CAD_TN_0911-508.pdf&sa=U&ved=2ahUKEwj_rvvU9pb6AhUGQUEAHVqNBvMQFnoECAIQAw&usg=AOvVaw2OcmlxMFDmI384_Cckmeet

https://en.m.wikipedia.org/wiki/Computer-aided_dispatch

**Comment by Wrexham244th** [comment]
Doesn't seem like it...

**Comment by phillf** [comment]
This isn't an issue. CAD has been used as an acronym in both law enforcement and similar industries as well as the design and construction industries.

**Comment by Wrexham244th** [comment]
> This isn't an issue. CAD has been used as an acronym in both law enforcement and similar industries as well as the design and construction industries.

I never said it was an actual issue.
