### ISSUE TITLE
Evaluate introducing Trello into our workflow.

### ISSUE THREAD

**Issue by KC1KAD** [StormlightTech/OpenCAD-php#45]
In order to improve efficiency at managing issues and pull requests, we should evaluate adding Trello into our backend workflow. Trello will also allow us to prioritize new features and consolidate development.

Should we implement Trello into our workflow?

**Comment by ItsAGeekThing** [comment]
This topic has been limited to collaborators only due to the outcome of this evaluation only affecting developers of OpenCAD.

**Comment by murfasa** [comment]
How can Trello be more efficient compared to just using GitHub projects? Do we really need the power of Trello over the simplicity and accessibility of GitHub projects?

(Just some questions to think about. Personally, I'm down with Trello)

**Comment by murfasa** [comment]
Interesting. How hard would it be to get Trello up and running and what would the requirements be?

**Comment by phillf** [comment]
Well I don't see the point in Trello if we are going to deploy JIRA. JIRA would solve this issue.

**Comment by Cambridgeport90** [comment]
I agree with this. plus, JIRA integrates right into BuildMaster, so that we can test different stages and environments as well. @phillf  knows what I'm talking about, I think, though it's not set up as of yet ... Getting there ... Hello, devOps.

**Comment by ItsAGeekThing** [comment]
@phillf that is true.
I completely forgot about the conversation we had regarding JIRA. Lack of sleep is getting to me. JIRA would be a better solution than Trello in all situations.

**Comment by murfasa** [comment]
I've been looking into it and JIRA does seem to be the most viable option.

**Comment by phillf** [comment]
@Cambridgeport90 Excellent point. We also have [Travis-CI](https://travis-ci.org) almost completely set up as well. Travis-CI is also deployed of on wiki repository to push changes to the wiki in the main repo.

**Comment by Cambridgeport90** [comment]
Interesting. I thought we were using TFS as build agent, though maybe that was just for some projects? I got confused; having our internal JIRA instance down has been hurting productivity and collaboration. Or maybe it's just me not being in the loop ... LOL But I'm pretty sure TFS was on server darkhill's agenda.
