### ISSUE TITLE
Report SENSITIVE Bug Reports (i.e. security vulnerabilities)

### ISSUE THREAD

**Issue by murfasa** [StormlightTech/openCAD-php#46]
Hey everyone,
We have a new system in place to handle **sensitive** bug reports (i.e. security vulnerabilities).

Simply send an email to security@opencad.io and the report will automatically be sent to the right place! Pretty cool, right?
Submit a bug report through this email as if you were sending one on GitHub. Thanks!

(Abuse of this email will get yourself blacklisted. 👎 )

**Comment by ItsAGeekThing** [comment]
This is already included in contributing.md.

![image](https://user-images.githubusercontent.com/7245209/30370091-8534fa30-9844-11e7-9d5a-577d1805b456.png)
![image](https://user-images.githubusercontent.com/7245209/30370096-89186ee8-9844-11e7-89ca-387f1addd4d8.png)
