### ISSUE TITLE
Not Operable from a Sub-Directory

### ISSUE THREAD

**Issue by phillf** [StormlightTech/openCAD-php#52]
### Enviorment Information
  - Operating System: Ubuntu 16.04 LTS
  - PHP Version: 7.0
  - MySQL Version: MariaDB 10.2
  - Web Server: Apache 2.4.18
    - Version: N/A (Pre RC1)
### Logs (if applicable)
Please use GitHub Gist.
  - PHP Logs:
  - Web Server Logs:
  - MySQL Logs:

### Expected behavior

Be functional when installed in a sub-directory.

### Actual behavior

When installed in a sub-directory multiple JS errors occur.

### Steps to reproduce behavior

1. Follow base installation instructions and install in a sub-directory (eg. opencad).
2. Login and navigate to the MDT (LEO/Rescue).

**Comment by ItsAGeekThing** [comment]
Fixed.
