### ISSUE TITLE
Unable to View current status in mdt.php

### ISSUE THREAD

**Issue by phillf** [StormlightTech/openCAD-php#56]
When viewing mdt.php users are unable to view their current status however they are able to change their status and it is accurately reflected in cad.php.

**Comment by ItsAGeekThing** [comment]
Temporarily hiding the Status Field in https://github.com/StormlightTech/openCAD-php/pull/57.
Hopefully we can have this resolved for RC2.

**Comment by termanator1128** [comment]
Issue has been resolved #97
