### ISSUE TITLE
cant access profile.php from admin.php

### ISSUE THREAD

**Issue by dwhirsch** [StormlightTech/openCAD-php#69]
When your on admin.php
you click on your user profile and click on My profile it comes to an error with 

/profile/profile.php

folder profile doesnt exist and profile.php is in main directory

**Comment by termanator1128** [comment]
This issue is now resolved.

**Comment by murfasa** [comment]
Below is the commit/merge used regarding the issue.
https://github.com/StormlightTech/openCAD-php/pull/88/commits
