### ISSUE TITLE
Add kudos to the original author.

### ISSUE THREAD

**Issue by exmex** [StormlightTech/openCAD-php#80]
Bad move. Add credits to the original author.
https://github.com/ossified/openCad

**Comment by phillf** [comment]
StormlightTech/openCAD-wiki#9 closes this.

**Comment by exmex** [comment]
Doesn't cut it. You're **LEGALLY** required to:
> 1. License and copyright notice **<-- Not done!**
> 2. State changes **<-- Not done!**
> 3. Disclose source (Done.)
> 4. Same license (Done.)

This was removed from index.php which is a no-go.
```php
 /**
	   Open source CAD system for RolePlaying Communities. 
	   Copyright (C) 2017 Shane Gill
	
	   This program is free software: you can redistribute it and/or modify
	    it under the terms of the GNU General Public License as published by
	    the Free Software Foundation, either version 3 of the License, or
	    (at your option) any later version.
	
	   This program comes with ABSOLUTELY NO WARRANTY; Use at your own risk.
	**/
```

**Comment by phillf** [comment]
@exmex Where should I state the changes?

**Comment by exmex** [comment]
You must clearly mark that this was originally Shane Gills work and that it was changed.
