### ISSUE TITLE
Profile location redirect. {FIX}

### ISSUE THREAD

**Issue by CrticalDanny** [StormlightTech/openCAD-php#89]
### Enviorment Information
  - Operating System: Mac
  - PHP Version: 7.1
  - MySQL Version: not sure :P
  - Web Server: linux
### Logs (if applicable)
Please use GitHub Gist.
  - PHP Logs:
  - Web Server Logs:
  - MySQL Logs:

### Expected behavior
redirect to previous page when pressing update within the profile page.

### Actual behavior

redirects to wrong page.

### Steps to Fix
you can fix it by changing the following line within profileActions.php

	header("Location: ../profile/profile.php");
to

	header('Location: ' . $_SERVER['HTTP_REFERER']);

**Comment by exmex** [comment]
Really?! This got merged!? LOL.

DON'T TRUST THE CLIENT!
https://security.stackexchange.com/questions/105389/dont-trust-the-client

Dont want to crosslink to laravel but:
github[DOT]com/laravel/framework/issues/14642#issuecomment-239395723

**Comment by ItsAGeekThing** [comment]
I have to agree with @exmex that this is bad practice.
I will be submitting a Pull Request in about 15 minutes that corrects this.
