### ISSUE TITLE
Password Update on Profile page{fix}

### ISSUE THREAD

**Issue by CrticalDanny** [StormlightTech/openCAD-php#95]
Two files need updating in order for this to work 

actionprofile.php
https://pastebin.com/QFsN7Nbt

and
profile.php
https://pastebin.com/p72Lid4K

**Comment by CrticalDanny** [comment]
DONT USE !!!! FOUND an issue

**Comment by CrticalDanny** [comment]
updated actionprofile.php

https://pastebin.com/JdaGna0y

**Comment by exmex** [comment]
Use pull-requests instead of posting pastebins..
