### ISSUE TITLE
Security {fix}

### ISSUE THREAD

**Issue by CrticalDanny** [StormlightTech/OpenCAD-php#98]
I didnt have time yet but the code needs to use the following,

mysql_real_escape_string used when insert into database  
htmlentities() used when outputting data into webpage
htmlspecialchars() used when inserting into database

If you want I could help with security in the upcoming days.

**Comment by phillf** [comment]
That would be much appreciated.

**Comment by exmex** [comment]
1. mysql_real_escape_string is deprecated. Since PHP5.5. (http://php.net/manual/en/function.mysql-real-escape-string.php)
2. It's not using mysql, it's using mysql**_i_**
3. No.
4. No.
5. No.
This is not fixing. This is hacking. Use prepared statements.

**Comment by CrticalDanny** [comment]
For the first one I agree and that was my bad on my behalf. However, htmlspecialchars() used when inserting into database should still be used.
